### ISSUE TITLE
Tx inputs and outputs hidden when too many

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neo-scan#105]
This is a [transaction](https://neoscan-testnet.io/transaction/cc9ecfd33f8522bc47ab9a8186661a07b32009c17d34223506df87719e0ad77f) with 2560inputs :)

This is a [transaction](https://neoscan-testnet.io/transaction/e38df7d8cb09b48adc709f0ac02f46e95ec957b3a147214250460483df4c4cc3) with 1000 outputs :)

The list of inputs/outputs cuts off at about 15th item on the list without any way to look at the rest. Inspecting the HTML shows that the rest of the list actually exists but is just hidden.

**Comment by lucianoengel** [comment]
Fixed :)
