### ISSUE TITLE
Really slow response time

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neo-scan#108]
![image](https://user-images.githubusercontent.com/9101245/34140649-0f127272-e431-11e7-9fc4-b85edfc633bb.png)

28s for an API call is pretty significant and might be related to your recent updates since it wasnt that slow previously.

But just to put it out there, the previous timing was still lagging quite a bit behind neon-wallet-db speed. (we talking about 2s here)

**Comment by steffenix** [comment]
We need to check the indexes in the db.

**Comment by lucianoengel** [comment]
@snowypowers, the unclaimed amount calculation takes some time for addresses that have a lot of unspent tx. I've removed that from the response object and things got much faster. Is that value necessary?

**Comment by snowypowers** [comment]
i wont need the unclaimed amt if im querying `get_balance`.

**Comment by lucianoengel** [comment]
Perfect then. Did you test if it's fast enough now?

**Comment by snowypowers** [comment]
1256ms on testnet. Yeah this is more like it 👍

**Comment by lucianoengel** [comment]
Great! I will close this then.
