### ISSUE TITLE
How can I get historic wallet amount?

### ISSUE THREAD

**Issue by franklili3** [CityOfZion/neo-scan#114]
The API has not the function of get historic wallet amount. How can I get historic wallet amount?

**Comment by lucianoengel** [comment]
Actually it has, please refer to the get_address method (https://neoscan.io/doc/Neoscan.Api.html#get_address/1) which gives you the full transaction and balance history.

**Comment by franklili3** [comment]
I don't want to get the transactions and balances of the specific address. I want to get the historical address amount. Example there are 1000000 addresses or 10000 addresses at 15th, Jan, 2018.
