### ISSUE TITLE
Replace "Neo Slack" link in footer with "Neo Discord"

### ISSUE THREAD

**Issue by msied** [CityOfZion/neo-scan#121]
As of December 10, 2017 CoZ moved its NEO community chat from slack to discord. The neoscan_web app needs to be updated to reflect this: https://www.reddit.com/r/NEO/comments/7is3oz/neo_slack_moving_to_discord/

![screen shot 2018-02-26 at 5 42 41 pm](https://user-images.githubusercontent.com/994683/36705942-7670a264-1b1c-11e8-9c8a-24165e066d8c.png)

I attempted this on my own, but there appears to be some non-standard knowledge involved with how the svg is generated, and how `.po` files are generated from `.pot`. Seems like low-hanging fruit for the original contributor @lucianoengel

**Comment by lucianoengel** [comment]
fixed :)
