### ISSUE TITLE
Block count -1 + tx page error.

### ISSUE THREAD

**Issue by slipo** [CityOfZion/neo-scan#124]
Trying to run latest master in docker connected to the privnet image and seeing this:

<img width="316" alt="screen shot 2018-03-04 at 3 14 48 pm" src="https://user-images.githubusercontent.com/327999/36950076-dea5d254-1fbe-11e8-9aa3-6375b7ef6bd3.png">

In console it seems to index all the blocks tho..

Also at http://localhost:4000/transactions/1 I see:
```
BadMapError at GET /transactions/1
expected a map, got: nil
```

**Comment by lucianoengel** [comment]
the counter shows -1 when the sync starts, it should update in 30s when the next msg from the server is broadcasted. The last build has a lot of changes and needs the DB to be reset. If you don't, it will find inconsistencies and won't be able to keep the sync process. It also uses http://notifications.neeeo.org/ to get nep5 notifications for main net, so it won't work for private net, you'd need to set up your own python rpc notifications database or simply return an empty list from that function.
