### ISSUE TITLE
** (Mix) The database for Neoscan.Repo couldn't be created: an exception was raised:

### ISSUE THREAD

**Issue by arrangilligan** [CityOfZion/neo-scan#126]
Anyone know about this? 
![screenshot from 2018-03-10 17-30-17](https://user-images.githubusercontent.com/11330026/37244412-ff3973da-2488-11e8-8c94-6b102f21c0ac.png)

**Comment by arrangilligan** [comment]
Erlang/OTP 21 [DEVELOPMENT] [erts-9.2.1] [source-88f654a] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe]

Mix 1.7.0-dev (24790a8) (compiled with OTP 21)

**Comment by lucianoengel** [comment]
Did you set up postgres with the same user and password as in  https://github.com/CityOfZion/neo-scan/blob/master/apps/neoscan/config/dev.exs ?

**Comment by yurii-cnw** [comment]
@arrangilligan Did you resolve the problem? I have the same one.
