### ISSUE TITLE
  ** (UndefinedFunctionError) function Poison.encode!/1 is undefined (module Poison is not available)

### ISSUE THREAD

**Issue by arrangilligan** [CityOfZion/neo-scan#127]
no poison module? 
![screenshot from 2018-03-10 21-36-26](https://user-images.githubusercontent.com/11330026/37246545-31bfc044-24ab-11e8-8520-4878454e1dff.png)

**Comment by lucianoengel** [comment]
I can't reproduce that error. Did you run mix deps.get?
