### ISSUE TITLE
How to deploy with docker

### ISSUE THREAD

**Issue by Keith-CY** [CityOfZion/neo-scan#135]
Thx for this project.

I'm not very familiar to docker so I follow the guide which works well locally

- `docker-compose up -d`

- `docker exec -it neoscan_phoenix_1 sh`

- `cd /data`

- `mix deps.get`

- `mix ecto.create && mix ecto.migrate`

Then I got an error ` The database for Neoscan.Repo couldn't be created: an exception was raised:` which seems to require `neoscan_*` in postgres docker.

Then the question is: 

How can I create the db in docker.

Thx again.

**Comment by lucianoengel** [comment]
Hello, I think you need to change the  hostname from localhost to postgres in the config files in the neoscan app.

**Comment by Keith-CY** [comment]
Now it works well, thank you.
