### ISSUE TITLE
tx fee values display

### ISSUE THREAD

**Issue by kokahunter** [CityOfZion/neo-scan#136]
From my visual inspection (haven't looked into the code), it seems like neo-scan displays no decimal places for fees. 
Because of that I see an issue for example with displaying following tx: https://neoscan.io/transaction/c920b2192e74eda4ca6140510813aa40fef1767d00c152aa6f8027c24bdf14f2

In: 40 
Out 39.999
Net fee displays zero but is 0.001.

**Comment by lucianoengel** [comment]
@kokahunter good catch! Thanks!
