### ISSUE TITLE
pending GAS transaction for >24h

### ISSUE THREAD

**Issue by avultur** [CityOfZion/neo-scan#137]
https://neoscan.io/address/AceWB7eDJsDZiJ99cUx6xbE341B9hs1v8s

**Comment by lucianoengel** [comment]
?

**Comment by avultur** [comment]
I sent 4.64224 GAS, on 2018-03-29 | 18:23:56, from Binance to Kucoin at AceWB7eDJsDZiJ99cUx6xbE341B9hs1v8s and it still has only 4 confirmations from 6 minimum required. Txid:89b27789d08720386e738d3661d022e52826aa0097c9add798c0516981fdb328
