### ISSUE TITLE
NEP-5 negative balance for smart contract addresses

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-scan#139]
Just discovered negative balances on two of our smart contract addresses:

https://neoscan.io/address/AZXKdEc2M73qeQMmPj2zmKJFDWmzQf8Gyr
https://neoscan.io/address/AepnUu5Aq4rhgejET6QFegxFR1HDScbTyK

They're showing negative balances of `-33,232,532.0` and `-1.26292e7`, respectively. Those are actually the total supply values for the NRVE and NRV tokens, so it looks like neoscan is treating the mint operations as debits from a 0 balance.

**Comment by lucianoengel** [comment]
Hello @brianlenz! This behavior is expected (for now). The notification database has only transfer notifications, not minting. So, addresses issuing tokens will always have a negative value that equals the total supply available. I can detect these negative values and display them as issued tokens, but in this first version I left it like this to track how things are working. I feared that corrupted data (missing transfers) would result in regular addresses having negative balances and then apear as they have issued tokens.  I still need to think in a good solution for that.

**Comment by brianlenz** [comment]
OK, gotcha! It's definitely challenging since these SC addresses could technically have a valid, positive NEP-5 token balance, too. That definitely makes it more challenging of a problem to solve. Sounds like you're on top of it 👍

**Comment by adrienmo** [comment]
duplicate with #246
