### ISSUE TITLE
Show NEP-5 symbol next to balance

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-scan#140]
It's awesome that neoscan supports NEP-5 tokens now. Nice work! One added touch that would be nice is if you displayed the token symbol next to the balance since people will be used to seeing the symbol (and not necessarily always the token name). I think it's cool having the token name as the header as you have right now, but it might be a nice added touch to show the symbol next to the balance displayed. 👍

**Comment by lucianoengel** [comment]
Thanks @brianlenz! Yeah that is a good idea, will change that! :)

**Comment by conscott** [comment]
I think it may also useful to have the scripthash as well, as many people will want to query with that. 

Consider something like Switcheo where the asset name is identical for SWH and SWTH. Getting balance of something like:

https://neoscan.io/api/main_net/v1/get_address/AdnW6aabas6pTndY1RTnZDPVxsC5Xe2JwC

just lists "Switcheo" twice, and it is ambigious which contract is token is which contract. 

Listing symbol _could_ make this less ambiguous but nothing prevents launching two contracts with the same symbol as far as I know. Contract Hash is the only way to really know which balance you are looking at.

**Comment by christophe238** [comment]
Really useful addition 👍
