### ISSUE TITLE
add method for transactions get_last_transactions_by_address

### ISSUE THREAD

**Issue by naetkss** [CityOfZion/neo-scan#142]
pls add method for transactions get_last_transactions_by_address

**Comment by lucianoengel** [comment]
there's alredy this method. https://neoscan.io/doc/Neoscan.Api.html#get_last_transactions_by_address/2

**Comment by evanjbowling** [comment]
@naetkss I have not successfully been able to use this api yet - anytime I change the page value I still get the same response from the server. See issue #160 that I created - hopefully this will get resolved soon

**Comment by lucianoengel** [comment]
it is resolved on api.neoscan.io
