### ISSUE TITLE
Where is the Assets in NEOSCAN?

### ISSUE THREAD

**Issue by AlleniCode** [CityOfZion/neo-scan#143]
![wechatimg58](https://user-images.githubusercontent.com/8855341/38977917-5ae3ebec-43e8-11e8-82ea-958bd63008d7.jpeg)

How to search the assets in NEOSCAN?

I can find the assets（资产）a few days ago, but I cannot find it now!

I want to search the token hash, how can I do this?

**Comment by lucianoengel** [comment]
It was taken out as requested by neo-council
