### ISSUE TITLE
Why can't I get a right transaction history in the test net?

### ISSUE THREAD

**Issue by AlleniCode** [CityOfZion/neo-scan#144]
My address: AR4iFxFdbjTkHKtStSKRvu5bgXXBcpZx9D

https://neoscan-testnet.io/api/test_net/v1/get_address_abstracts/AR4iFxFdbjTkHKtStSKRvu5bgXXBcpZx9D/1

**Comment by lucianoengel** [comment]
Because testnet is resyncing. Always check the last block to see if the chain is fully synced

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
