### ISSUE TITLE
the nep5 transcation is not correct

### ISSUE THREAD

**Issue by bitcodernull** [CityOfZion/neo-scan#159]
https://neoscan.io/transaction/20a75e9da1d7d1d9a5a73f9fd75a510cc78831a69fdc0d6ce1c5185d96f19a79

the transaction have not transfered tokens

**Comment by lucianoengel** [comment]
this is a issue with people using transfer without notifications. If there's no notifications the neo-python notifications DB won't have a notification and therefore neoscan won't have it as well. There's no solution for this problem right now, as I'd have to find and add the missing transfers manually.

**Comment by bitcodernull** [comment]
thanks

the transaction is not really successful ?
the tokens is not transfered between users?

**Comment by lucianoengel** [comment]
This is a explorer, it has nothing to do with the transaction itself. If the tokens aren't in your wallet then they were transferred.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bitcodernull** [comment]
i know it has do nothing with the transaction :)

i think the explore maybe have a bug, the transaction is not really successful ,but the explore show the token has been  transfered
