### ISSUE TITLE
`get_last_transactions_by_address` API not paginating

### ISSUE THREAD

**Issue by evanjbowling** [CityOfZion/neo-scan#160]
So far, all queries to the above API return the exact same set of transactions no matter which `page` value I use. The [`get_last_transactions_by_address` docs](https://neoscan.io/doc/Neoscan.Api.html#get_last_transactions_by_address/2) don't describe the format of the `page` value, but I could tell by [examining the code](https://github.com/CityOfZion/neo-scan/blob/master/apps/neoscan/lib/neoscan/api/api.ex#L1136) that it looks to be an integer.

Q: Can you tell me how I should use the `page` path param to successfully use this API?

## Attempts so far

* [https://neoscan.io/api/main_net/v1/get_last_transactions_by_address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV/1](https://neoscan.io/api/main_net/v1/get_last_transactions_by_address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV/1)
* [https://neoscan.io/api/main_net/v1/get_last_transactions_by_address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV/2](https://neoscan.io/api/main_net/v1/get_last_transactions_by_address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV/2)
* [https://neoscan.io/api/main_net/v1/get_last_transactions_by_address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV/15](https://neoscan.io/api/main_net/v1/get_last_transactions_by_address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV/15)
* [https://neoscan.io/api/main_net/v1/get_last_transactions_by_address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV/45](https://neoscan.io/api/main_net/v1/get_last_transactions_by_address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV/45)

## Other APIs to get address and transaction data succeed

I know that I have a valid address because I can see the 61 transactions on the neoscan.io UI: [https://neoscan.io/address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV](https://neoscan.io/address/AN2tgwQWHovJxkRsvxApxHB1EiWaKVBaxV). I can also hit other API endpoints and successfully gather all transaction data via:

* [`get_address`](https://neoscan.io/doc/Neoscan.Api.html#get_address/1)
* [`get_transaction`](https://neoscan.io/doc/Neoscan.Api.html#get_transaction/1)

I would prefer to have a paginated approach to fetching transaction data so I'm hoping you can help me with this API.

**Comment by lucianoengel** [comment]
Ok, caught the bug! thanks for pointing it out :)

**Comment by evanjbowling** [comment]
This issue is still not resolved - the queries above still all resolve to the same values. Can you look into it again and reopen this issue until it is resolved?

Thanks!
