### ISSUE TITLE
500 Internal Server Error for API get_address()

### ISSUE THREAD

**Issue by soundasleep** [CityOfZion/neo-scan#165]
https://neoscan.io/api/main_net/v1/get_address/ATQt1VwQN9nkprx7XKXTsbdATg3t3eBjKX

Is currently returning a 500 Internal Server Error. It appears to be throwing this error for any valid address.

**Comment by lucianoengel** [comment]
it worked for me.

**Comment by soundasleep** [comment]
It's working now. I guess it was down for a while. Thanks!
