### ISSUE TITLE
Show block number and info timestamp on transaction

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neo-scan#179]
On transactions route (ex: https://neoscan.neocompiler.io/transactions/1) it would be useful to have the block number (with a link) together with the "completed on" (so a general panoram on how often blocks are being used and how much load is carried). 
Another useful information would be to have the REAL timestamp when the information is added to neoscan and when it was added on the blockchain (I don't know if this information is available, but I hope so :D). This would be also useful to visualize the current delays on information processing.

**Comment by lucianoengel** [comment]
There's a link to the block and the completed on information as well, in the transaction page. I don't see a point in showing the time in which it was added to neoscan, everytime I resync the chain that changes. Also, the time it was added on the blockchain and the time it was completed are just the block timestamp. There's no time difference in transactions inside a block. Your goal is determine how much time neoscan takes to process new blocks?

**Comment by igormcoelho** [comment]
I just realized I could use neoscan API to get_block timestamp (in original times), that was enough for my use case. Thanks a lot!
