### ISSUE TITLE
Please start using tags

### ISSUE THREAD

**Issue by igormcoelho** [CityOfZion/neo-scan#183]
Please, it would be very nice to have some tags on this project, indicating "apparently" stable versions. It's hard to have all master versions considered stable :)

**Comment by adrienmo** [comment]
Hi @igormcoelho, I am not sure to understand your request. 

Master branch is stable, pull request will be only merged after code quality/unit test/ integration test/ test on staging is done. As soon as a feature is ready, it should be merged to master and deployed to production ASAP, this is continuous delivery. 

Is there something I am missing here?

**Comment by igormcoelho** [comment]
Hi @adrienmo it's just that I have never seen any project before that do not use release tags :) I'm not Software Engineering expert, but usually this is made for showing to the community that the product (in that version) was heavily tested and it is stable, also showing that one specific API is stable (and won't change too much, according to Semantic Versioning). Since there are no tags, we endup creating external manual "tags", indicating which commit we "trust" (because we also have tested ourselves). If we always receive the master branch, there may be some situation in the future that some backwards compatibility is lost, and that may break our system (that automatically pulls neo-scan repository).
But as I have said, I'm no expert, it was just strange to see no tags, but if that's the way you work, we can get used to it (and continue to mark the tags manually) :)
