### ISSUE TITLE
Issue in balances (both on site and via API)

### ISSUE THREAD

**Issue by sdbkwilia** [CityOfZion/neo-scan#197]
Hi, 

Found this while perusing the API but the website is also affected.
Address used for testing: AHJTn3Mqmrfh6Vf77VqQqXNmcfvTaQZyWw.

So looking this up in neotracker brings up the correct values:
https://neotracker.io/address/AHJTn3Mqmrfh6Vf77VqQqXNmcfvTaQZyWw.

Bringing this up in neoscan gets the following:
https://neoscan.io/address/AHJTn3Mqmrfh6Vf77VqQqXNmcfvTaQZyWw

Which as you can see looks a bit off. Now this looks mostly like a formatting issue.
![balances](https://user-images.githubusercontent.com/7511402/40615572-9953acf6-6287-11e8-9c88-d8bd5ea03dea.png)

Until you dive into the API for this address and use the get_Balance call:
https://neoscan.io/api/main_net/v1/get_balance/AHJTn3Mqmrfh6Vf77VqQqXNmcfvTaQZyWw

This shows that besides formatting there is plain invalid information there. Take for example the Red Pulse Token amount:
The neonscan site and api claim this 'starts with 35*. While in reality it should at least start with 75*. It feels like separators aren't handled well, or amounts are being multiplied to 'not have to deal with this' but then only the 'right X' characters are being returned. 

So I'm not sure if it's stored incorrectly and simply returned 'wrong' or also stored incorrectly when it's being processed.

**Comment by sdbkwilia** [comment]
So should the fix be done in a different project (neo-python/core) or is the issue pertinent to this project specifically? Or is it a 'will not fix' type answer? A little ambiguous..

**Comment by lucianoengel** [comment]
This is a problem with non-standard transfer methods that do not log it to the vm. If there's no log for some transfers, there's no way of explorers or neo-python to see that a transfer has been made. I can't say where exactly each missing transfer error comes from, but it's not neoscan related.

**Comment by sdbkwilia** [comment]
Right, thanks for explaining that. So rather plainly put I guess this will/should be closed and I should not rely on neoscan for address balances (for now). Would that be a correct assumption?

**Comment by lucianoengel** [comment]
Correct. The only reliable way to get correct nep5 token balances from any address is to make a call to the VM through InvokeScript.
