### ISSUE TITLE
Testnet balance not showing on neo-scan API

### ISSUE THREAD

**Issue by conscott** [CityOfZion/neo-scan#199]
For the address `AL8abuPwBMmmvaj1EttZr6B6R7NDoXBsm6`

The RPC interface gives correct testnet balance:

```bash
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"getaccountstate", "params": ["AL8abuPwBMmmvaj1EttZr6B6R7NDoXBsm6"], "id": 3}' seed2.neo.org:20332
```

but NeoScan API does not:
[https://neoscan-testnet.io/api/test_net/v1/get_balance/AL8abuPwBMmmvaj1EttZr6B6R7NDoXBsm6](https://neoscan-testnet.io/api/test_net/v1/get_balance/AL8abuPwBMmmvaj1EttZr6B6R7NDoXBsm6)

Curious if anyone knows why.

**Comment by lucianoengel** [comment]
Yes, testnet is still syncing with the new version. Once sync is done it should be fine

**Comment by conscott** [comment]
Is there anywhere I can get a progress update on that? Is this something that takes hours or days?

**Comment by lucianoengel** [comment]
yes, and yes. Just watch the last block on the landing page. There's a date and time in the block as well, you can see when it reaches present time.
