### ISSUE TITLE
Adding nep5 token to neoscan

### ISSUE THREAD

**Issue by aibric1407** [CityOfZion/neo-scan#211]
Hi,

I know this is not the place for questions but I have tried on discord and did not get any answer so I am hoping to find help here.

I have neoscan docker running with private net. After creating and deploying new token I am able to see it in my wallet but I am not able to see that token on neoscan. When trying to getBalance with neonjs using neoscan my token balance is not visible, it is visible only if I ping directly privnet.

My question is how can I add/register/issue token on neoscan so I can query token balance with neoscan api?

**Comment by lucianoengel** [comment]
if it is the last version of neo-local priv-net docker(that includes the neo-python notifications DB) it should pick nep5 tokens automatically. There's no support for nep5 in the older version.
