### ISSUE TITLE
Network fees and System fees 

### ISSUE THREAD

**Issue by NinaCrypto** [CityOfZion/neo-scan#212]
Talking about Neoscan explorer >transaction information: I have pretty clear in mind what the system fees are, but can you explain what the network fees are and what is the difference between these 2 fields? 

Also, what is the difference between an invocation and a contract? (already google it and search in the whitepaper but didn't find the difference). Thank you awesome community

**Comment by lucianoengel** [comment]
Network fees are paid to consensus nodes and are meant to be used for priority execution of transactions. Sys fee is the price for neo-vm smart-contract executions. Invocations is a transaction that invokes a smart-contract and a contract transaction is a transference of UTXO assets.
