### ISSUE TITLE
Help Needed Neo Explorer

### ISSUE THREAD

**Issue by D0rk80** [CityOfZion/neo-scan#220]
Hello,

I'm having a few issues 

1. When the server reboots I have to go to the /neo-scan-master and run mix phx.server (not sure how to get this to run automatically but get this error after it runs for a bit:  heap_alloc : Cannot allocation 2343242342343 byts of memory (of type "old_heap"). I can browse the site for while before it does a crash dump.

2.  When I run mix phx.server using terminal other errors I see but can browse the site before it crashdumps.
2018-06-21 16:23:17:360 [ error] [nonode@nohost] enconnrefused
2018-06-21 16:23:17:361 [ error] [nonode@nohost] connection_timeout
2018-06-21 16:23:17:362 [ error] [nonode@nohost] enconnrefused
2018-06-21 16:23:17:363 [ error] [nonode@nohost] enconnrefused

3. Is there paid support options here?

**Comment by lucianoengel** [comment]
Hello @D0rk80 
1- Whats the machine configuration of your server? 
2 - That's normal, it is filtering out non-responsive neo-nodes.
3 - No, there isn't. This is a public project.

**Comment by D0rk80** [comment]
1. 4 vcpus, 8gb of ram, ubuntu OS.
2.  How do you start the site without having to run the command. Why does it run out of memory when running from terminal?

**Comment by lucianoengel** [comment]
I don't know why you are running out of memory, 8gb is more than enough. You need to investigate further, as I can't reproduce that error. 

There's no way to start it without giving it a command... the feature that you're looking for might be the supervisor package (http://supervisord.org)
