### ISSUE TITLE
Where blockchain is stored

### ISSUE THREAD

**Issue by SergeyAnkarenko** [CityOfZion/neo-scan#223]
Where blockchain is stored? How can I specify blockchain directory.

**Comment by adrienmo** [comment]
the blockchain is stored in a custom format which is the postgres database, what is your use case ?

**Comment by SergeyAnkarenko** [comment]
I want to run my own server to use neoscan api. I have already running python-rpc on the same server. I was thinking if I can make neoscan and python-rpc to reference the same database.

**Comment by SergeyAnkarenko** [comment]
Or at least use locally running python-rpc to synchronize blockchain. It must be much faster

**Comment by lucianoengel** [comment]
there's no way to do that as is. They are completely different databases.

**Comment by SergeyAnkarenko** [comment]
Yes, I see. Thank you

**Comment by SergeyAnkarenko** [comment]
How can I specify blockchain directory? I am using ubuntu 16.04 server and I want to store the blockchain on specific ssd disk.

**Comment by lucianoengel** [comment]
There's no blockchain "directory", it uses postgres as database. Please, this is not a issue with neoscan, if you have any doubts setting up a postgres database there's plenty of documentation and places to look for help already.

**Comment by SergeyAnkarenko** [comment]
Now it's very  clear for me, thank you very much for detailed explanation
