### ISSUE TITLE
Previous block showing "no data"

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-scan#224]
Hey guys, it is just some minor details.

Since the previous block of the last block of a page is in another page O.o, the previous block wont exist.
ehauehauea

https://github.com/CityOfZion/neo-scan/blob/9b6327e817b40d25a53faa777f00b7c035ad94e1/apps/neoscan_web/lib/neoscan_web/views/blocks_view.ex#L75

I would like to fix, but I am not expert in these kind of scripts.

**Comment by lucianoengel** [comment]
yeah, we show "no data" because these blocks are in memory, and we'd need a DB query for the missing block.  I'll see what we can do, maybe keep an extra block in memory as well

**Comment by adrienmo** [comment]
@lucianoengel I am planning to do a sql query to solve that (WINDOW function: https://www.postgresql.org/docs/9.1/static/tutorial-window.html)

**Comment by vncoelho** [comment]
Thanks, @lucianoengel  and @adrienmo.

Furthermore, congratulation for the great project you are going carrying out.
Go for it. 
There are just some minor things from now on.
