### ISSUE TITLE
Error when do it mix ecto.create

### ISSUE THREAD

**Issue by albertfle** [CityOfZion/neo-scan#225]
Hi, 

I do it all commands  but when I try mix ecto.create, I get this error:

(Mix) Could not compile dependency :websocket_client, ".mix/rebar3 bare compile --paths "neo-scan/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile websocket_client", update it with "mix deps.update websocket_client" or clean it with "mix deps.clean websocket_client"

Can you help me?

**Comment by lucianoengel** [comment]
Did you try the recommendations?

**Comment by albertfle** [comment]
yes, I try it all recommendations.

**Comment by lucianoengel** [comment]
Sorry, I can't reproduce this error, you need to investigate further.

I'd try to check if your system has enough memory or reinstalling rebar. Take a look at https://github.com/elixir-lang/elixir/issues/3857

**Comment by albertfle** [comment]
I get now a new error when I do the command mix ecto.migrate:

[root@neoscan-test neo-scan]# mix ecto.create
The database for Neoscan.Repo has already been created
[root@neoscan-test neo-scan]# mix ecto.migrate
2018-06-26 12:52:05.468 [info] [nonode@nohost] == Running Neoscan.Repo.Migrations.Blocks.change/0 forward
2018-06-26 12:52:05.469 [info] [nonode@nohost] create table blocks
** (Postgrex.Error) ERROR 42704 (undefined_object): no existe el tipo Â«jsonbÂ»
    (ecto) lib/ecto/adapters/sql.ex:200: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:96: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:96: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:104: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:102: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:26: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:128: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:73: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/migrator.ex:261: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:83: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
