### ISSUE TITLE
Neo-scan lagging behind

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-scan#227]
Hey, people.

I am not sure if I am correct.
But I imagine that the Neo-Scan is lagging behind because of the notifications, which was coming from neo-neopy-rest and, apparently, recently coming from neo-cli-forked-rest (https://github.com/localhuman/neo-cli/tree/plugin-notification-restapi).

Considering the current importance that neoscan has in the EcoSystem, it is important to have the neo-scan api in a beautiful manner. Congrulations @lucianoengel, for everything you have been doing.

I think that you should/could design something else. Sorry to mention that, because it would represent a little bit of efforts. Count with us! 
Since I already saw a branch that you are redesigning some little things, I thought that it could be a nice moment for this:

1.  Synchronize neo-scan blocks info only from neo-cli RPC's (this is the natural dependency, please, do not include an additional one). In this sense, do not allow any NP5 notification status to block/delay the update/sync of your db.
2. Keep using the Rest api to get the notifications and "optimize" the notification db as you are currently doing in an efficient manner (a part of the thousands of call per seconds.. :P).

This would imply that neo-scan could vary the dozens of RPC that the NeoEcosystem current have. In this sense, I believe that your system will almost never stay lagged behind the csharp RPC's.
It is very important.

- For allowing a working and smooth user experience, you could depict a message saying that the specific block/transaction could not be "translated" (thus, the user will not see the tokens transfer and etc)...But, at least, he would see that the transaction went thought the system.
    - Additionally, we could design a tool in the frontend for interpreting the block for that cases.

What do you think?

**Comment by lucianoengel** [comment]
Hello @vncoelho thanks for the suggestions. We thought about some of these ideas in the refactor. follow ups:

1- This would cause the explorer to be "apparently" synced when in reality there's missing data. What's best from the user perspective: have an explorer out of sync or a synced one that do not show his transfers? I think that the latter would cause much more impact on users. The not "translated" idea is interesting, we can explore that, but I'd change it to "waiting notifications" or something :P

2- The refactoring should increase the sync time greatly, we're still testing it because we're pretty sure that the notification DB can't handle that many calls.

**Comment by vncoelho** [comment]
1- But it would be not missing data, @lucianoengel. All data will be there, but just without the notifications.
    * I think that "waiting notifications" is the best approach for now, because would require any new implementation. It would just show the "raw tx" and, then, display the message.
     On the other hand, translate it in the frontend is a very light task! @igormcoelho can give us an insight about his. But, basically, is deserializing the tx. It is almost instantaneous for someone that loads the page with the TX (on-the-fly).

2- I like but do not like this notification db, it is creating something not necessary! Let's believe in the power of the frontend devices :dagger:

**Comment by hal0x2328** [comment]
This is likely solved by :  https://github.com/CityOfZion/neo-scan/pull/383
@adrienmo Is this okay to close?

**Comment by adrienmo** [comment]
@hal0x2328 yes let's close it
