### ISSUE TITLE
"Internal server error" when searching for wallet address

### ISSUE THREAD

**Issue by lonelystowner** [CityOfZion/neo-scan#228]
When searching for my specific wallet address, I receive "Internal Server Error" in black text on an all white page. There is no other information. I am able to search for other wallet addresses I've used, i am able to click on any wallet that I see on Neoscan, but when searching for my specific wallet I get the error. Every other wallet seems to load just fine. I have triple checked that I am using the correct address and I have also tried different devices. I am able to view the same wallet on Neotracker and antchain.

**Comment by lucianoengel** [comment]
Hello @lonelystowner  can you share your address so we can debug?

**Comment by lonelystowner** [comment]
my fault I meant to put that in the OP.

AZX5wCRTcPvdJF3Uavsrq4KWYNif6FreB4

**Comment by vncoelho** [comment]
@lucianoengel, adding something to the discussion.
In particular, this is a multi-sig address generated by first designed csharp privatenet with python genesis script.

**Comment by lonelystowner** [comment]
If there is anything I can do to assist, please let me know. @lucianoengel  @vncoelho

**Comment by vncoelho** [comment]
Hey @lonelystowner, in fact, it is a very good question you did.

I have been always wondering why this address had this error.
I would like to check this address for the mainnet, we should have a similar one there.

**Comment by lonelystowner** [comment]
This should be a mainnet address already @vncoelho. I created this wallet a bit over a year ago and I created it using NEON wallet and my Ledger. If there is anything you would like me to try or do, let me know.

**Comment by vncoelho** [comment]
I see, sorry, my mistake.
Because the first characteres of this base58 address are similar to the ones of the privatenet. In fact, the same internal error problem happens there.

**Comment by lonelystowner** [comment]
Interesting @vncoelho I never tried it on testnet before. I wonder why just my address has this issue. I am not much of a dev though so I really have no idea, haha.

**Comment by vncoelho** [comment]
Ok, anyway, if you want to check balance and it is bothering you, you could use direct RPC calls while it is not fixed.

**Comment by lonelystowner** [comment]
Will do! Thanks @vncoelho

**Comment by adrienmo** [comment]
I think this is now resolve with the new version:

https://neoscan.io/address/AZX5wCRTcPvdJF3Uavsrq4KWYNif6FreB4
