### ISSUE TITLE
store transaction value as integer or decimal type instead of float

### ISSUE THREAD

**Issue by adrienmo** [CityOfZion/neo-scan#253]

**Comment by yongjiema** [comment]
please assign it to me, thanks!

**Comment by adrienmo** [comment]
OK, I'll let you handle it :)

**Comment by yongjiema** [comment]
I am doing the change, I think it's better to return string instead float for API, and Phoenix convert decimal as string by default. Currently, some APIs return number as string, and some APIs return as float, any idea have a good catch for it? The difference is showing as below:

`string`
- get_address_abstracts
- get_address_to_address_abstracts

`float`
- get_balance
- get_claimable
- get_last_transactions_by_address
- get_transaction
- get_unclaimed

**Comment by yongjiema** [comment]
Sounds good! I will follow the current API specification for now, and make it easy to change later.
