### ISSUE TITLE
The unit testing is calling the actual servers as token URLs are not matched

### ISSUE THREAD

**Issue by yongjiema** [CityOfZion/neo-scan#267]
The unit testing `get/3` is calling the actual servers as below token URLs are not matched:

- http_calls_test.exs: http://notifications1.neeeo.org/v1/tokens
- http_poison_wrapper.ex: http://notifications1.neeeo.org/v1/tokens?page=1

**Comment by adrienmo** [comment]
Hello @yongjiema good catch, can you add this fix to your pull request? Thanks!

**Comment by yongjiema** [comment]
@adrienmo  My pleasure, what about my pull request #266? the fix will change the same place in `http_calls_test.exs`, I worry about the conflict here.

**Comment by adrienmo** [comment]
#266 is now closed :)
