### ISSUE TITLE
Invalid height is returning from get_node_height/1

### ISSUE THREAD

**Issue by yongjiema** [CityOfZion/neo-scan#268]
The function `get_node_height/1` calls the API `getblockcount` from blockchain, so current height should be `blockcount - 1`.

**Comment by adrienmo** [comment]
@yongjiema wording is indeed important, I guess we can rename the function name to get_block_count/1

**Comment by yongjiema** [comment]
@adrienmo Sounds great! Would you like the pull request from me? The changes will be as following:

1. Change `get_current_height` to `get_block_count`;
2. Update `get_node_height`;
3. Update the unit testing.

**Comment by adrienmo** [comment]
@yongjiema sounds like a plan, please feel free to submit a PR :)

**Comment by yongjiema** [comment]
@adrienmo PR is submitted.
