### ISSUE TITLE
The transaction vin order should be kept

### ISSUE THREAD

**Issue by yongjiema** [CityOfZion/neo-scan#269]
For example, the sequence of vin is [4 NEO, 3 NEO, 40 NEO]
- UI: https://neoscan.io/transaction/8E23D99DA5D2BC836D9D31846AC26A33C9CDD07ACDF2568CCE8BCA71912AFD54
- API: https://neoscan.io/api/main_net/v1/get_transaction/8e23d99da5d2bc836d9d31846ac26a33c9cdd07acdf2568cce8bca71912afd54

but the sequence of vin from blockchain is [40 NEO, 3 NEO, 4 NEO]
- Blockchain: http://seed1.redpulse.com:10332?id=0&method=getrawtransaction&params=["8e23d99da5d2bc836d9d31846ac26a33c9cdd07acdf2568cce8bca71912afd54", 1]

**Comment by adrienmo** [comment]
@yongjiema while vout order is important as it is used to specify a vin, I think the sequence of vin has little importance, I guess it will be better to just use the same order returned by the nodes, but except from display point of view is there another reason that will make this bug a higher priority?

**Comment by yongjiema** [comment]
I just noticed it will be potential issue here.

**Comment by adrienmo** [comment]
I'm changing the label to enhancement as I don't see any urgent reason to deal with it. I guess a way to solve this issue is to change the vin mode to add an "index" field, this index can be derived from the json response of the node for a block. When displaying the vins we can then just do an "order_by" index for the vin.

**Comment by yongjiema** [comment]
I agree with the plan, it's not urgent for me either. Do you welcome the PR from me for the enhancement?

**Comment by adrienmo** [comment]
@yongjiema yes you can do a PR, but it will require a resync so it is harder to handle in release cycle

**Comment by yongjiema** [comment]
I just encounter a issue related to it, some unit testings are failed due to the order is different.

**Comment by adrienmo** [comment]
@yongjiema can you precise which test is failing?
