### ISSUE TITLE
Cannot identify the asset if more the one assets have the same name from some APIs.

### ISSUE THREAD

**Issue by yongjiema** [CityOfZion/neo-scan#305]
Currently the following APIs return asset name under `asset` field only:

- `get_balance`
- `get_transaction`

and the others APIs (e.g. `get_address_abstracts`) return asset id under `asset` field.

**Comment by yongjiema** [comment]
@adrienmo Can we return the asset hash under `asset` field for these APIs if users pass `asset_hash` with `true` from request?

**Comment by adrienmo** [comment]
@yongjiema I actually think the whole API must be revamped, right now the frontend does not use the API, I think it would be better to unify the usage for neoscan frontend and other service that rely on it. I'm not sure we need to touch the current API, I would rather work on #248 and #249 . Do you have a use case for this API change?

**Comment by yongjiema** [comment]
@adrienmo sounds better :thumbsup:
