### ISSUE TITLE
Transfers and balances being logged transactions that failed due to gas limit reached

### ISSUE THREAD

**Issue by nickfujita** [CityOfZion/neo-scan#306]
It appears that the notifications db is logging NEP5 Transfer events for transactions that failed to complete due to free gas limit reached. In the following example, 3 NEP5 transfers to separate wallet addresses were bundled into a single transaction. The first 2 transfers ran in the smart contract, emitted Transfer Notification events, but the third transfer failed due to the free gas limit being reached. This ultimately resulted in the smart contract not persisting the state of the previous 2 transfers because the transaction as a whole failed, but the Transfer Notifications were still recorded be the db being used to store NeoScan transfer events.

Example account:
https://neoscan.io/address/APSWMGidPkdm3YhgNP4TWgaXDrHzPvvaso

Shows a balance of 100 SDT, but a call directly to the contract `balanceOf` method shows a balance of only 50 SDT.

First failed transaction with 3 transfers bundled into a single transaction:
https://neoscan.io/transaction/954d38d72b5db68754882fc0161de8f9c8e64dd7757dfefb017ac5a5f3c7a182

Second successful transaction with only 2 transfers bundled into a single transaction:
https://neoscan.io/transaction/b1301c179f4ee86f0516877b10db21ef13f2dfcb30dcba5e9ad6d0b7d03a6a54

I verified that the originating wallet still retained the full balance after the first failed transaction, according to directly calling `balanceOf` on the contract, but showed a deducted balance on NeoScan.
https://neoscan.io/address/AbTVteEBP3uetrppAcUGhhCAtMj5UYUNgp

As you can see from the source account, it now has a large negative balance because of a bunch of failed transactions with 3 bundled transfers that went over the free GAS limit. This is because the erroneous transaction notifications were stored, making the NeoScan db think that more was transferred out of the address then actually happened.

**Comment by nickfujita** [comment]
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "txid": "0x954d38d72b5db68754882fc0161de8f9c8e64dd7757dfefb017ac5a5f3c7a182",
    "vmstate": "FAULT, BREAK",
    "gas_consumed": "10.879",
    "stack": [
      {
        "type": "Integer",
        "value": "1"
      },
      {
        "type": "Integer",
        "value": "1"
      },
      {
        "type": "Integer",
        "value": "5000000000"
      },
      {
        "type": "ByteArray",
        "value": "11c117317b00bba8d7284008289a142fcf23b3d7f1"
      },
      {
        "type": "InteropInterface"
      }
    ],
    "notifications": [
      {
        "contract": "0xa4f408df2a1ec2a950ec5fd06d7b9dc5f83b9e73",
        "state": {
          "type": "Array",
          "value": [
            {
              "type": "ByteArray",
              "value": "7472616e73666572"
            },
            {
              "type": "ByteArray",
              "value": "d7e8de04ad0ff281e3f4591a9c942814306246c3"
            },
            {
              "type": "ByteArray",
              "value": "5417533cee6a1ba1c4783340ec228be57663883d"
            },
            {
              "type": "ByteArray",
              "value": "00f2052a01000000"
            }
          ]
        }
      },
      {
        "contract": "0xa4f408df2a1ec2a950ec5fd06d7b9dc5f83b9e73",
        "state": {
          "type": "Array",
          "value": [
            {
              "type": "ByteArray",
              "value": "7472616e73666572"
            },
            {
              "type": "ByteArray",
              "value": "d7e8de04ad0ff281e3f4591a9c942814306246c3"
            },
            {
              "type": "ByteArray",
              "value": "f5f66afcc7cbbb0d9217b2b6ed1dbab5d468b7b2"
            },
            {
              "type": "ByteArray",
              "value": "00f2052a01000000"
            }
          ]
        }
      }
    ]
  }
}
```

The log for the failed transaction appears to have returned with a `vmstate` of `FAULT, BREAK`, which should indicate that the transaction for these notifications has failed.

**Comment by adrienmo** [comment]
@nickfujita thanks for your detailed report. After investigation it seems the notification server is reporting unsuccessful transfer leading neoscan to register them. The problem can be solved with one of those two solutions:
1- Notification server is fixed, in this case we just have to do a full resync of neoscan
2- neoscan implements its own VM to get the transfer information instead of relying on 3rd party services.

I believe solution 1 will be implemented first 😄 
I will leave the issue open to track when the resync will be done.

**Comment by adrienmo** [comment]
fixed with resync
