### ISSUE TITLE
Return invalid amount from get_address_abstracts API if a transaction has network fee

### ISSUE THREAD

**Issue by yongjiema** [CityOfZion/neo-scan#310]
e.g. for the transaction `ee6f489503137bc80f81502be6d0ec8558df59797b7279aa873624e9e96b5587` from the address `APdjiDV4EmJjRHV1pTQT6fFN3iPVswb7RP` to address `AKNywXYJMKpoEgbfG8wij2Tae5uQ78pg7n`:

- actual amount: 0.00215951
- expected amount:  0.0021595

**Comment by adrienmo** [comment]
I believe the amount are correct, the 0.00000001 missing is actually the network fee. Maybe we should have a visual to make it part of the transaction, right now it is just written under, maybe it is not that clear.

**Comment by yongjiema** [comment]
Maybe I mentioned it's not clear from previously, I mean the amount from the get_address_abstracts API (https://api.neoscan.io/api/main_net/v1/get_address_abstracts/APdjiDV4EmJjRHV1pTQT6fFN3iPVswb7RP/1) is `0.00215951`.

But actually, the address `APdjiDV4EmJjRHV1pTQT6fFN3iPVswb7RP` transferred `0.0021595` to `AKNywXYJMKpoEgbfG8wij2Tae5uQ78pg7n` (https://neoscan.io/transaction/EE6F489503137BC80F81502BE6D0EC8558DF59797B7279AA873624E9E96B5587)

Is the amount should be `0.0021595` from get_address_abstracts?

**Comment by adrienmo** [comment]
yes indeed, I will investigate

**Comment by adrienmo** [comment]
right now an intermediate solution is to remove the network fee from the gas transfer (special case for gas transfers) only one abstract will be shown and the transaction for the network fee will be omitted from the list.

this a temporary solution, a better solution will be to list the gas transfer and the network fee. Similar of what we have when we do a neo transfer with network fee.

**Comment by yongjiema** [comment]
I agree with you as it shows difference between UI and database.
