### ISSUE TITLE
feature: Add route to return supply of nep5 tokens for CMC listings

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-scan#324]
Currently, all projects in neo ecosystem must maintain a method to resolving their supply in order to list on CMC.  This feature would add a route for a get which returns the total supply of a requested nep5.

/supply/{{scriptHash}}

**Comment by adrienmo** [comment]
any details on the return format?

**Comment by adrienmo** [comment]
@lllwvlvwlll can you provide the documentation link of CMC? Can it be a POST request or only GET? what kind of payload should it return?

**Comment by adrienmo** [comment]
I'm closing this issue for now, please reopen it if you have the information/ it is still needed
