### ISSUE TITLE
Can't synchronize

### ISSUE THREAD

**Issue by SergeyAnkarenko** [CityOfZion/neo-scan#331]
At some point neoscan has stopped synchronizing

![image](https://user-images.githubusercontent.com/6827668/44303445-d8339780-a349-11e8-82ac-659e006c3761.png)

![image](https://user-images.githubusercontent.com/6827668/44303523-4036ad80-a34b-11e8-9aa3-a732908b8d6f.png)

![image](https://user-images.githubusercontent.com/6827668/44303473-690a7300-a34a-11e8-9055-5e58321761cf.png)

After restart it synchronizes a couple of blocks and then throws the same error.

**Comment by adrienmo** [comment]
it seems you are running a very old version of neoscan, can you try with a newer version?
