### ISSUE TITLE
invalid balance is displayed

### ISSUE THREAD

**Issue by SergeyAnkarenko** [CityOfZion/neo-scan#332]
https://neoscan.io/address/AMbsZvvmzBMtNN6ukux8AYqL2JCndRtd8i
https://neotracker.io/address/AMbsZvvmzBMtNN6ukux8AYqL2JCndRtd8i

Neoscan is displaying invalid neo balance

**Comment by adrienmo** [comment]
The missing transaction is in the block "2,623,809", the chain was stuck on this block explaining the error from neoscan, a full resync of the chain will solve the problem

**Comment by adrienmo** [comment]
resync done.
