### ISSUE TITLE
Add support for NEP5 tokens

### ISSUE THREAD

**Issue by lucianoengel** [CityOfZion/neo-scan#35]

**Comment by vladucu** [comment]
I can take a stab at adding NEP5 assets this week
@lucianoengel let me know if that's cool and if you have any thoughts on the implementation that I should take into consideration

**Comment by lucianoengel** [comment]
Sure! @dvdschwrtz (@bjornborg in slack) is also into this, he can give you a better idea then myself I think. :)

**Comment by bjornborg** [comment]
Hmmmmmm

**Comment by gligoran** [comment]
Has there been any progress on this?

**Comment by lucianoengel** [comment]
next version is introducing nep5 tokens
