### ISSUE TITLE
Syncing blocks halts on NEP-5 token transfer/mint

### ISSUE THREAD

**Issue by jeroenptrs** [CityOfZion/neo-scan#354]
In tested neo-local instances, neo scan stops syncing blocks when performing a `transfer` implementation (`mintTokens`, `deploy` that sends tokens to the owner, `transfer`, ... ) on a NEP-5 contract.

This was confirmed by @WyattMufson on a separate occasion

**Comment by WyattMufson** [comment]
I can reproduce the issue on the latest version of neo-local with [this repo](https://github.com/Ryucoin/ryu-ico-template). I run `deploy` and then `transfer`. It might have to do with the fact that when I transfer neo-scan has it so the owner wallet has a negative balance (I forgot to update `totalSupply` when I minted it for the testnet - [example wallet](https://neoscan-testnet.io/address/AQdEfNx9av8yRcGbX9ntpmznAk1YzGLzzo)

**Comment by WyattMufson** [comment]
After a little bit more investigation it seems that it's the `OnTransfer` call that is halting neo-scan. Previously my `deploy` function didn't cause it to stop even though it was transferring tokens. Once I added the line `OnTransfer(None, TOKEN_OWNER, TOKEN_INITIAL_AMOUNT)` in the `deploy` function it now stops neo-scan.

**Comment by adrienmo** [comment]
Seems the problem comes from the python notification server that returns transfer amount as integer instead of returning it as string for the endpoint http://server/v1/notifications/block/index

**Comment by WyattMufson** [comment]
Can confirm that the recent release of neo-python fixes the neo-scan issue in neo-local. Opened a PR to update to the newer version https://github.com/CityOfZion/neo-local/pull/67

**Comment by adrienmo** [comment]
I will close this issue then
