### ISSUE TITLE
neoscan-testnet.io block height is not increasing

### ISSUE THREAD

**Issue by ppsdang** [CityOfZion/neo-scan#355]
neoscan-testnet.io block height is not increasing.

I am testing my application, I send some NEO from my wallet to application address.

Transaction is not getting confirmed as block height is not increasing.

**Comment by adrienmo** [comment]
Hello, currently the neo testnet is not working, you can check on the monitor page here: http://monitor.cityofzion.io/ (need to choose TestNet). So for the neoscan part it is working properly, blocks will be fetched as soon as testnet is working again. For more information about the testnet I invite you to contact the neo team (https://neo.org/).
