### ISSUE TITLE
run neo-scan pointed to mainnet or testnet instance 

### ISSUE THREAD

**Issue by some-dev** [CityOfZion/neo-scan#356]
Based on documentation i can't figure out how to configure neo-scan to run mainnet/testnet instead of private network.
Is there any way to do it?

I want to use api for retrieving utxo and balances

**Comment by adrienmo** [comment]
Can you describe your setup? Do you have elixir/postgres installed on your computer? Or do you try to use neo-local?

**Comment by some-dev** [comment]
i'm trying to run neo-scan on kuberntes. I believe i can run elixir/posgresql. But based on documentation (readme) i can't figure out how to configure neo-scan instance to work with mainnet/testnet instead of private network.

**Comment by adrienmo** [comment]
@some-dev you can refer to this docker-compose: https://github.com/CityOfZion/neo-local/blob/master/docker-compose.yml

you can just update the value of the variable `NEO_NOTIFICATIONS_SERVER` and `NEO_SEEDS`. If both are empty it will connect directly to the mainnet, if you want to use the test net you can set the variable to those values:

``` 
NEO_SEEDS: "http://api.otcgo.cn:20332;https://seed1.neo.org:20331;http://seed2.neo.org:20332;http://seed3.neo.org:20332;http://seed4.neo.org:20332;https://test1.cityofzion.io;https://test2.cityofzion.io;https://test3.cityofzion.io;https://test4.cityofzion.io;https://test5.cityofzion.io;http://seed5.neo.org:20332"
NEO_NOTIFICATIONS_SERVER:  "http://notiftest1.neeeo.org/v1"
```

Be sure that your postgresql databse is empty before changing servers url

**Comment by KickSeason** [comment]
i want to use it with my private chain. how should i config ?
