### ISSUE TITLE
Transactions of get_last_transactions_by_address, have empty attributes

### ISSUE THREAD

**Issue by phetter** [CityOfZion/neo-scan#368]
neoscan-testnet.io/api/test_net/v1/get_last_transactions_by_address/ is not producing results with attributes array when given transaction is known to have attributes.

Proof of comparison between two results is available upon request.

https://neoscan-testnet.io/api/test_net/v1/get_last_transactions_by_address/APJnYRic9fYo1bLAdrqDbwrsnqoUD92dWo/0

versus

https://neoscan-testnet.io/transaction/93a9481dd0391be55c9bb8a04caae4fb24fe963b45e72723fa68026ac14dc83b

**Comment by adrienmo** [comment]
Maybe you can provide the address because right now none of the URLs given work
