### ISSUE TITLE
API returns 0 amount for self-send transactions

### ISSUE THREAD

**Issue by osmirnov** [CityOfZion/neo-scan#380]
This seems like a NeoScan bug as the API request itself returns "amount":"0" value.

Request:
https://neoscan.io/api/main_net/v1/get_address_abstracts/AaSvMiKMQqkev2VctudCNVu3t8Tjd1xKpG/1

Result:
```
{
  "entries": [{
    "txid":"6b45d56eb5013c922154ac11958cfe7de89d275c67b3ab692f5ad3909c3bbdec",
    "time":1541888575,
    "block_height":2947374,
    "asset":"602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7",
    "amount":"0",
    "address_to":"AaSvMiKMQqkev2VctudCNVu3t8Tjd1xKpG",
    "address_from":"AaSvMiKMQqkev2VctudCNVu3t8Tjd1xKpG"},
]
```
Apparently this consistently occurs for self-send txs, regardless of the amount. Another example, [this transaction](https://neoscan.io/transaction/67bd2f5beebbcbe24029ba4082392c1c53095931e438a1b017c333a84d9c5a9a) for 766 NEO results in amount: "0" as well, when observing it in [the API call](https://neoscan.io/api/main_net/v1/get_address_abstracts/ALHxkfrT78M4nV9b7dCUVfN9mpnT5SrEPk/2).

**Comment by adrienmo** [comment]
If you are transferring fund to yourself, there is virtually no transfer. That's why neoscan displays 0 in this case.  Could you describe your use case?

**Comment by osmirnov** [comment]
@adrienmo neoscan displays 0 only in api. The UI for [the transaction](https://neoscan.io/transaction/6B45D56EB5013C922154AC11958CFE7DE89D275C67B3AB692F5AD3909C3BBDEC) shows the fact of the transfer. It is true for [the same transaction](https://neotracker.io/tx/6b45d56eb5013c922154ac11958cfe7de89d275c67b3ab692f5ad3909c3bbdec) on neotracker.
My business case arose from the linked issue in neon-wallet. Unfortunately, I had no time to see how behaves official APIs as neo-cli in this case. So I speak mostly from inconsistency in neotracker UI and API.

**Comment by adrienmo** [comment]
The UI and the API do not show the same thing.

The UI display that some gas has been sent, and that some gas has been received
The API "display" the result of the transaction (sent - receive), it only show 1 thing and not 2 things. The front-end is currently not using the API to get its data, we will work on new endpoint to make the front-end only use API calls, in which case your problem will be solved.
