### ISSUE TITLE
Use getapplicationlog to get NEP-5 transfers

### ISSUE THREAD

**Issue by adrienmo** [CityOfZion/neo-scan#382]
We want to remove the dependency of neoscan on the notification server, to be able to do it, we can use the `getapplicationlog` command from NEO RPC nodes

**Comment by hal0x2328** [comment]
Making a note here - @canesin just mentioned on Slack that the plan is to merge the notifications feature into the Neoscan API. @deanpress suggested to make the API backwards-compatible with the old notifications server to make migrating dApps/tools easier for anyone who was already depending on that.
