### ISSUE TITLE
Neo-scan missing some txids and showing different balances

### ISSUE THREAD

**Issue by xxedocxx** [CityOfZion/neo-scan#384]
Example below

**Address:** 
AMcBtJWPoJp4td2N1bjBZ3VazDoN9rwCmP

**Missing txid:** 
13db3c4271f4a0c05048a468bb5d3ac7b663bf73e76d679a9411045b6bab983a

**Neotracker:**
https://neotracker.io/tx/13db3c4271f4a0c05048a468bb5d3ac7b663bf73e76d679a9411045b6bab983a

**Neoscan:**
Can't find

**Comment by adrienmo** [comment]
yes, the block 2,980,963, is missing from the neoscan database. I am deploying a new synced version soon (tomorrow).

**Comment by adrienmo** [comment]
fixed with resync
