### ISSUE TITLE
Syn has stopped at block 2654918

### ISSUE THREAD

**Issue by truongtrau** [CityOfZion/neo-scan#386]
![image](https://user-images.githubusercontent.com/22745195/49570621-c06c3780-f969-11e8-8dd7-cde7c497023e.png)

**Comment by truongtrau** [comment]
@ambethia @Ejhfast @metachris @rockacola help me please. thank so much!

**Comment by hal0x2328** [comment]
Is this still an issue for you or were you able to finally get it to sync?
