### ISSUE TITLE
Neotracker and Neoscan are not synced, tokens do not appear in wallet

### ISSUE THREAD

**Issue by EGFR** [CityOfZion/neo-scan#387]
I was sent 400 NEX tokens to my address. I can see the tokens in Neotracker, but not in other explorers such as Neoscan and O3. I also cannot see the tokens in Neon wallet and O3 wallet. Did I lose my funds?

any suggestions or solutions?

it has been more than 36 h.

I appreciate any help!

https://neotracker.io/address/AeZPrQzbK9sgKSB18QaTCYFiNN8KRgPRKZ
https://neoscan.io/address/AeZPrQzbK9sgKSB18QaTCYFiNN8KRgPRKZ
https://o3.network/scan/#AeZPrQzbK9sgKSB18QaTCYFiNN8KRgPRKZ

**Comment by hal0x2328** [comment]
It appears that neoscan currently has correct balance of NEX (zero).  neotracker has 399, which is incorrect according to the network nodes.
