### ISSUE TITLE
Show blocktime in ms

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-scan#397]
With recent improvements on the consensus, mempool and p2p, we might be able to create some networks with less than 1s of blocktime.
I mean, in local private network, at least. But that is very useful for IoT applications as we are currently investigating.

Could you design a flag or something in docker for us to adjust the blocktime calculus? It would be great if we could see that in ms.

**Comment by uvmetal** [comment]
You want to be able to see this in the front end neoscan web block explorer correct? Here, for example:

![image](https://user-images.githubusercontent.com/7162325/60914316-e84cb200-a24e-11e9-881a-032b1f0ae8fa.png)
