### ISSUE TITLE
[enhance] twitter card for neoscan

### ISSUE THREAD

**Issue by vincentgeneste** [CityOfZion/neo-scan#404]
it would be awesome if neoscan could have metadata for twitter card so that it shows the name / logo instead of something blank at the moment if it's shared on twitter.

it's as simple as adding 

    <meta name="twitter:card" content="summary"/>
    <meta name="twitter:description" content="Your home for all NEO related blockchain information" />
    <meta name="twitter:title" content="NEOSCAN"/>
    <meta name="twitter:url" content="https://neoscan.io/">
    <meta name="twitter:image" content="....logourl..."/>

Would render better instead of having this.

<img width="620" alt="Screen Shot 2019-04-08 at 17 06 55" src="https://user-images.githubusercontent.com/25534589/55764524-c14ccd00-5a20-11e9-987a-2b3fbca28243.png">

**Comment by adrienmo** [comment]
#407 has been merged
