### ISSUE TITLE
Notification server have been removed

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-scan#405]
Congratulations for the great job, @adrienmo.

I just saw that dependencies related to notification servers have been removed, right?
In this sense, all queries now are being directed to neo-cli c# clients with NEP5 plugin, correct?

I think that it will surely allow a better experience in long-term use.

**Comment by adrienmo** [comment]
Hi @vncoelho yes that's correct, it does not need the notification server anymore. The query can be directly done the the c# client and they need to have the function `getapplicationlog` enabled which I guess is the nep5 plugin. Can I close the issue or do you need something about this?

**Comment by vncoelho** [comment]
Perfect, @adrienmo. Nice job.
I already upgraded our system, thanks.
