### ISSUE TITLE
get_all_nodes returning deprecated neonexchange.org URLs

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neo-scan#419]
https://api.neoscan.io/api/main_net/v1/get_all_nodes is returning nodes with the URL *.neonexchange.org which no longer have a valid SSL certificate, which causes errors for neon-js users or anyone else using the Neoscan API to select the best node at any given moment.

 I believe the neonexchange.org domain is deprecated and those nodes should be changed to point to *.nash.io instead.

**Comment by uvmetal** [comment]
As you can see from the following it appears one would need to update the following file to make this change.

![image](https://user-images.githubusercontent.com/7162325/60402062-adac9080-9b4f-11e9-82a3-50af1fed5f73.png)

**Comment by uvmetal** [comment]
Correction, it appears the file https://raw.githubusercontent.com/CityOfZion/neo-mon/master/docs/assets/mainnet.json does not contain the exchange links. The nash servers just need to be added.

**Comment by uvmetal** [comment]
Correction, I wasn't synchronized. I'm reviewing to correct the discussion thread now.
