### ISSUE TITLE
Add API for getting unclaimed transactions

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neo-scan#59]
In order to build claimTransactions easily, I will need the following information:

- Transaction ID
- Amount of gas claimable from this transaction

The amt of gas claimable can be calculated by taking the difference between the block that generated the coin and the block that spent the coin.

EG:
 http://testnet-api.wallet.cityofzion.io/v2/address/claims/ALq7AWrhAueN6mJNqk6FHJjnsEoPRytLdW

The `total_claim` property at the end is useful but not necessary.

**Comment by lucianoengel** [comment]
Ok, added to the new version

**Comment by snowypowers** [comment]
any examples? is it live for testing? I tried the API but dont see them

**Comment by lucianoengel** [comment]
No, it will go live in the new design version that we're working on.

![image](https://user-images.githubusercontent.com/1004935/31999395-d53a68c8-b971-11e7-8cf1-7534a354e6e4.png)

![image](https://user-images.githubusercontent.com/1004935/31999425-ecb80de8-b971-11e7-9c4b-fc87aef9abbd.png)

**Comment by snowypowers** [comment]
alright, will wait for the new version then :)

**Comment by lucianoengel** [comment]
Are these calls enough for what you need? Let me know if you need anything else ;)

**Comment by snowypowers** [comment]
oh for `get_balance` we need to know the index of the coin in the txid. 

```
{
  "index": 1,
  "txid": "e241fa7935f8e7160983ef3dcd5fb2808cbba6d51593c5521287767c0b97be96",
  "value": 2
}
```

In a transaction, there are many outputs. We need to know exactly which output we are referring to. The `index` here refers to the index in the outputs array.

**Comment by snowypowers** [comment]
similarly for `get_claimable` we will also need the index to point to the correct coin in question.

**Comment by lucianoengel** [comment]
Ok! But I kept the chain "n" nomenclature

![image](https://user-images.githubusercontent.com/1004935/32001109-8ae56c90-b977-11e7-863d-8c826a8c7387.png)

![image](https://user-images.githubusercontent.com/1004935/32001133-9c0be1ac-b977-11e7-99cf-7e25cf5cd85a.png)

**Comment by snowypowers** [comment]
OK. As long as the data is there that's okay. I can work with that on my side of implementation.

**Comment by lucianoengel** [comment]
@snowypowers API is online in neoscan.io!
