### ISSUE TITLE
Design Better GenStage Pipeline

### ISSUE THREAD

**Issue by lucianoengel** [CityOfZion/neo-scan#7]
The current blockchain synchronization process uses a GenStage pipeline as follows:

![add_block 1](https://user-images.githubusercontent.com/1004935/29618389-5fd3feaa-87ee-11e7-93ec-eaf49e65ed82.jpg)

The problem is that a block don't have a maximum transactions count, neither transactions have a maximum number of inputs or outputs. Blocks with a great amount of transactions or with big transactions therefore flood memory with too many operations. A good pipeline design I believe, should ask for a maximum demand of addresses to update, which would ask for outputs, inputs and claims, which would ask for transactions and them for blocks. However, each stage doesn't know how many transactions/blocks it should ask for to fulfill the demand, so there must be a queue for each.

**Comment by lucianoengel** [comment]
current solution seems yo be handling well in production. This will be kept open though, if anyone wants to give a try and improve.

**Comment by adrienmo** [comment]
The refactored version do not use a genserver anymore, a Task.async_stream approach is more "lightweight" and is better suited for our use case
