### ISSUE TITLE
Wrong claim numbers

### ISSUE THREAD

**Issue by snowypowers** [CityOfZion/neo-scan#84]
During testing for neon-js, I noticed that the claim numbers are wrong for neoscan. 

https://neoscan.io/api/main_net/v1/get_claimable/ATsmYxUsJaU1AcZm3RCcTAhrvYUNMPaCvq:
```
{
    "claimable": [
        {
            "value": 825,
            "unclaimed": 6.50298,
            "txid": "9adfbd49621c45bae64e8f11e2cd9a42c5330d9f39220390d6b7b5081bf606f6",
            "start_height": 1485981,
            "n": 0,
            "end_height": 1584386
        },
        {
            "value": 30,
            "unclaimed": 0.0208548,
            "txid": "d24f3a0d7d62d08165b30be5a0352f1bcf883be6cee182c125bc2138c2a17ceb",
            "start_height": 1575820,
            "n": 0,
            "end_height": 1584386
        },
        {
            "value": 25,
            "unclaimed": 0.175424,
            "txid": "bae94b0741a1982b0a1d1246fcfa62f88e3b746f89856f91efcd3db6b519e790",
            "start_height": 1496799,
            "n": 0,
            "end_height": 1584386
        },
        {
            "value": 29,
            "unclaimed": 0.13658043,
            "txid": "8d287bee9482a64e4b5034feddfb12611229bc7e7ebefbea8830dba73ff6f3b7",
            "start_height": 1525639,
            "n": 0,
            "end_height": 1584386
        }
    ],
    "address": "ATsmYxUsJaU1AcZm3RCcTAhrvYUNMPaCvq"
}
```

http://api.wallet.cityofzion.io/v2/address/claims/ATsmYxUsJaU1AcZm3RCcTAhrvYUNMPaCvq
```
{
    "address": "ATsmYxUsJaU1AcZm3RCcTAhrvYUNMPaCvq",
    "claims": [
        {
            "claim": 650291400,
            "end": 1584386,
            "index": 0,
            "start": 1485981,
            "sysfee": 992,
            "txid": "9adfbd49621c45bae64e8f11e2cd9a42c5330d9f39220390d6b7b5081bf606f6",
            "value": 825
        },
        {
            "claim": 17542200,
            "end": 1584386,
            "index": 0,
            "start": 1496799,
            "sysfee": 992,
            "txid": "bae94b0741a1982b0a1d1246fcfa62f88e3b746f89856f91efcd3db6b519e790",
            "value": 25
        },
        {
            "claim": 13657811,
            "end": 1584386,
            "index": 0,
            "start": 1525639,
            "sysfee": 983,
            "txid": "8d287bee9482a64e4b5034feddfb12611229bc7e7ebefbea8830dba73ff6f3b7",
            "value": 29
        },
        {
            "claim": 2085240,
            "end": 1584386,
            "index": 0,
            "start": 1575820,
            "sysfee": 980,
            "txid": "d24f3a0d7d62d08165b30be5a0352f1bcf883be6cee182c125bc2138c2a17ceb",
            "value": 30
        }
    ],
    "net": "MainNet",
    "total_claim": 683576651,
    "total_unspent_claim": 36360
}
```

I would assume neon-wallet-db is giving the correct numbers because I have counter checked it with neo-gui:

![image](https://user-images.githubusercontent.com/9101245/32825127-b1001cba-ca1e-11e7-85e4-e9ccfb4142d6.png)

**Comment by lucianoengel** [comment]
@snowypowers  can you test if it's working now?

**Comment by snowypowers** [comment]
looks to be good

**Comment by SephirothLT** [comment]
It happened again  @snowypowers

**Comment by lucianoengel** [comment]
@SephirothLT please, if you think there's something wrong give more information about what is happening. This is a place for code bug reporting, not costumer support.

**Comment by SephirothLT** [comment]
[http://api.wallet.cityofzion.io/v2/address/claims/AQXEiXqFExFfGYe5WwbyCX3cSxYk31WVJd](http://api.wallet.cityofzion.io/v2/address/claims/AQXEiXqFExFfGYe5WwbyCX3cSxYk31WVJd)
RESULT:
`{
    "address": "AQXEiXqFExFfGYe5WwbyCX3cSxYk31WVJd",
    "claims": [],
    "net": "MainNet",
    "total_claim": 0,
    "total_unspent_claim": 0
}`


NEOSCAN:[https://neoscan.io/address/AQXEiXqFExFfGYe5WwbyCX3cSxYk31WVJd](https://neoscan.io/address/AQXEiXqFExFfGYe5WwbyCX3cSxYk31WVJd)

**Comment by lucianoengel** [comment]
@SephirothLT there's nothing wrong with the above.

**Comment by SephirothLT** [comment]
first link   :"total_unspent_claim": 0
 neoscan link: 0.00000252 Unclaimed Gas
the number is not matched

**Comment by lucianoengel** [comment]
yes because that's the unavailable+available amount. The api only return the available amount.

**Comment by lucianoengel** [comment]
that's the unavailable amount. It doesn't matter. It's wrong because api.wallet is deprecated and 4000 blocks behind the current block height

**Comment by SephirothLT** [comment]
so  the" api.wallet" can't use anymore?

**Comment by SephirothLT** [comment]
so  the problem is doesn't matter?   the block synced completed then  the result is right? please 
@lucianoengel

**Comment by lucianoengel** [comment]
there's no problem, just use neoscan.

**Comment by SephirothLT** [comment]
Thanks!
